### ISSUE TITLE
[Doc] Update wording of 4bit to GPTQ and add qlora

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#71]
**Problem**

Previously, 4bit quant meant GPTQ. However, due to the new release of qlora, there can be some confusion on this subject (like here https://discord.com/channels/1104757954588196865/1111279858136383509/1111846381355802744). 

**TODO**

- [x] Add new column for qlora
- [x] Rename 4bit quant
- [ ] Evaluate qlora on other architectures

**Comment by winglian** [comment]
`Add new column for qlora` fixed in #77 
`Rename 4bit quant` fixed in #75

**Comment by NanoCode012** [comment]
`Evaluate qlora on other architectures` can be done in other issues/prs.
